name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install

      - name: Install Box
        run: composer global require humbug/box

      - name: Create PHAR
        run: box compile

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: composer-integrity.phar
          artifactContentType: application/x-php